### ISSUE TITLE
Python sample: Object of type EnvironHeaders is not JSON serializable

### ISSUE THREAD

**Issue by isdal** [gcpevents/eventsforcloudrun#5]
I played around with GCS events and python. The sample python sample and throws this stack trace when the event comes in:
```
Traceback (most recent call last): 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app response = self.full_dispatch_request() 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request rv = self.handle_user_exception(e) File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception reraise(exc_type, exc_value, tb) 
File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise raise value 
File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) 
File "/app/app.py", line 15, in event_handler **print(json.dumps(request.headers))** File "/usr/local/lib/python3.7/json/__init__.py", line 231, in dumps return _default_encoder.encode(obj) 
File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode chunks = self.iterencode(o, _one_shot=True) File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode return _iterencode(o, 0) File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default raise 

TypeError(f'Object of type {o.__class__.__name__} ' **TypeError: Object of type EnvironHeaders is not JSON serializable**
```

**Comment by grant** [comment]
Thanks for the issue. I'll look at this and see why it's throwing:
`Object of type EnvironHeaders is not JSON serializable`

**Comment by grant** [comment]
We now have official samples in our official repo:

https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/eventarc

We do not `json.dumps` which would produce this error.
